version: '3.8'

services:
  chambabot:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chambabot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
